// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function() {
    var config;
    config = this.config;
    return this.PlatformSubdomain = (function() {
      function PlatformSubdomain() {
        this.parseSubdomainRequest = __bind(this.parseSubdomainRequest, this);
        this.update = __bind(this.update, this);
      }

      PlatformSubdomain.prototype.currentSubdomain = null;

      PlatformSubdomain.prototype.update = function() {
        return $.ajax({
          url: "" + config.url + "/platform/subdomain.json",
          cache: false,
          success: this.parseSubdomainRequest
        });
      };

      PlatformSubdomain.prototype.parseSubdomainRequest = function(data) {
        this.currentSubdomain = data != null ? data.subdomain : void 0;
        return $(document).trigger("subdomain:change", this.currentSubdomain);
      };

      return PlatformSubdomain;

    })();
  })();

}).call(this);
