// Generated by CoffeeScript 1.6.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function() {
    var config;
    config = this.config;
    return this.TimesheetVersion = (function() {
      function TimesheetVersion() {
        this.togglePolling = __bind(this.togglePolling, this);
        this.pollComplete = __bind(this.pollComplete, this);
        this.parseCurrentVersion = __bind(this.parseCurrentVersion, this);
        this.update = __bind(this.update, this);
      }

      TimesheetVersion.prototype.pollLength = 20;

      TimesheetVersion.prototype.shouldPoll = false;

      TimesheetVersion.prototype.update = function() {
        clearTimeout(this.pendingPoll);
        if (!this.subdomain) {
          return;
        }
        return $.ajax({
          url: "" + config.protocol + "://" + this.subdomain + config.domain + "/time/weekly/check_for_updates",
          cache: false,
          success: this.parseCurrentVersion,
          complete: this.pollComplete
        });
      };

      TimesheetVersion.prototype.parseCurrentVersion = function(data) {
        if (data == null) {
          return;
        }
        if (data.polling_frequency != null) {
          this.pollLength = data.polling_frequency;
        }
        if (data.timesheet_version !== this.currentVersion) {
          this.currentVersion = data.timesheet_version;
          return $(document).trigger("timesheetVersion:change");
        }
      };

      TimesheetVersion.prototype.pollComplete = function() {
        if (!this.shouldPoll) {
          return;
        }
        return this.pendingPoll = setTimeout(this.update, this.pollLength * 1000);
      };

      TimesheetVersion.prototype.startPolling = function(subdomain) {
        this.subdomain = subdomain;
        this.shouldPoll = true;
        return this.update();
      };

      TimesheetVersion.prototype.stopPolling = function() {
        this.shouldPoll = false;
        this.subdomain = null;
        this.currentVersion = null;
        return clearTimeout(this.pendingPoll);
      };

      TimesheetVersion.prototype.togglePolling = function(evt) {
        var subdomain;
        subdomain = evt.data;
        if (subdomain) {
          return this.startPolling(subdomain);
        } else {
          return this.stopPolling();
        }
      };

      return TimesheetVersion;

    })();
  })();

}).call(this);
